In [ ]:
import pandas as pd

:

In [ ]:
df =  pd.read_csv(r"C:\Users\gadis\Downloads\olist\olist_sellers_dataset.csv")

:

In [ ]:
df.info()

:

In [21]:
df.shape

(3095, 4)

In [22]:
df.describe()

       seller_zip_code_prefix
count             3095.000000
mean             32291.059451
std              32713.453830
min               1001.000000
25%               7093.500000
50%              14940.000000
75%              64552.500000
max              99730.000000

In [23]:
df.duplicated().sum()

np.int64(0)

In [24]:
df.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [25]:
df['seller_state'].unique()

array(['SP', 'RJ', 'PE', 'PR', 'GO', 'SC', 'BA', 'DF', 'RS', 'MG', 'RN',
       'MT', 'CE', 'PB', 'AC', 'ES', 'RO', 'PI', 'MS', 'SE', 'MA', 'AM',
       'PA'], dtype=object)

In [26]:
df['seller_city'].unique()

array(['campinas', 'mogi guacu', 'rio de janeiro', 'sao paulo',
       'braganca paulista', 'brejao', 'penapolis', 'curitiba', 'anapolis',
       'itirapina', 'tubarao', 'lauro de freitas', 'imbituba', 'brasilia',
       'porto seguro', 'guaruja', 'tabatinga', 'salto', 'tres de maio',
       'belo horizonte', 'arapongas', 'sao bernardo do campo', 'tatui',
       'garopaba', 'camanducaia', 'tupa', 'guarulhos',
       'sao jose dos pinhais', 'sao ludgero', 'sao jose', 'piracicaba',
       'porto alegre', 'congonhal', 'santo andre', 'osasco', 'valinhos',
       'joinville', 'saquarema', 'barra velha', 'petropolis',
       'santo antonio da patrulha', 'ponta grossa', 'santana de parnaiba',
       'sao carlos', 'ibitinga', 'barueri', 'caxias do sul', 'araguari',
       'contagem', 'jaragua do sul', 'lages - sc', 'bento goncalves',
       'catanduva', 'ribeirao pires', 'jaboticabal', 'echapora', 'cotia',
       'rio do sul', 'sorocaba', 'pradopolis', 'itaborai', 'mirassol',
       'birigui', 'assis', 'jaguariuna', 'araraquara', 'macae',
       'rio claro', 'londrina', 'ribeirao preto', 'tres coracoes',
       'nhandeara', 'orleans', 'cuiaba', 'formosa do oeste', 'santos',
       'santa terezinha de goias', 'arvorezinha', 'guiricema', 'caruaru',
       'franca', 'salvador', 'diadema', 'itaquaquecetuba',
       'lencois paulista', 'carapicuiba', 'uruacu', 'itajai', 'loanda',
       'maringa', 'ferraz de vasconcelos', 'limeira', 'claudio',
       'niteroi', 'osvaldo cruz', 'sao goncalo', 'jaciara',
       'balenario camboriu', 'timbo', 'jacutinga', 'fortaleza',
       'ferraz de  vasconcelos', 'mirandopolis', 'bauru', 'jacarei',
       'itu', 'laranjeiras do sul', 'videira', 'florianopolis',
       'itapecerica da serra', 'mamanguape', 'ponte nova', 'goioere',
       'pederneiras', 'itapevi', 'goiania', 'campina grande',
       'estancia velha', 'resende', 'maua', 'caratinga', 'auriflama/sp',
       'cafelandia', 'uba', 'sao paulo / sao paulo',
       'sao jose do rio preto', 'porto ferreira', 'tres coroas',
       'blumenau', 'mogi das cruzes', 'jaci', 'laranjal paulista',
       'americana', 'sertanopolis', 'apucarana', 'colombo',
       'vicente de carvalho', 'mesquita', 'sao pauo', 'cascavel',
       'fazenda rio grande', 'taboao da serra', 'sao jose dos campos',
       'toledo', 'marechal candido rondon', 'jundiai', 'mandirituba',
       'suzano', 'vespasiano', 'santa rosa', 'sao joaquim da barra',
       'santo antonio de posse', 'uruguaiana', 'campanha', 'piracanjuba',
       'concordia', 'santa rita do sapucai', 'barretos', 'indaiatuba',
       'nilopolis', 'pompeia', 'barro alto', 'são paulo', 'praia grande',
       'luiz alves', 'brusque', 'criciuma', 'jales', 'atibaia',
       'rio branco', 'barra mansa', 'marilia', 'bahia', 'taubate',
       'cascavael', 'monteiro lobato', 'viana', 'paraiba do sul',
       'mococa', 'sao roque', 'passos', 'francisco beltrao', 'tocantins',
       'porto belo', 'nova iguacu', 'icara', 'lajeado', 'horizontina',
       'votorantim', 'campo bom', 'monte alto', 'fernandopolis',
       'pedreira', 'poa', 'divinopolis', 'santa barbara d´oeste',
       'canoas', 'mombuca', 'sete lagoas', 'campo do meio',
       'cordeiropolis', 'uberlandia', 'santa barbara d oeste',
       'volta redonda', '04482255', 'aracatuba', 'monte siao', 'garuva',
       'bonfinopolis de minas', 'cosmopolis', 'pocos de caldas',
       'artur nogueira', 'joao pessoa', 'dois corregos', 'araquari',
       'novo hamburgo, rio grande do sul, brasil', 'floranopolis',
       'sumare', 'guaira', 'cachoeiro de itapemirim', 'serrana',
       'rolandia', 'congonhas', 'sao  jose dos pinhais', 'boituva',
       'mairipora', 'guaimbe', 'parai', 'aperibe', 'jaguaruna',
       'vila velha', 'juiz de fora', 'fronteira', 'novo horizonte',
       'pilar do sul', 'itajobi', 'cariacica / es', 'prados', 'mucambo',
       'montes claros', 'vicosa', 'porto velho', 'sao jose do rio pardo',
       'pato branco', 'sao joao del rei', 'presidente prudente',
       'paracambi', 'serra negra', 'sao caetano do sul', 'bom jardim',
       'serra redonda', 'sao francisco do sul', 'betim', 'imbituva',
       'guaratuba', 'teresina', "sao miguel d'oeste", 'california',
       'japira', 'foz do iguacu', 'nova friburgo', 'itau de minas',
       'oliveira', 'sabara', 'pedrinhas paulista', 'votuporanga',
       'holambra', 'ararangua', 'pinhais', 'pato bragado', 'carazinho',
       'arinos', 'sao pedro', 'lages', 'ampere', 'itauna', 'mogi mirim',
       'curitibanos', 'brasilia df', 'mogi das cruses', 'hortolandia',
       'ipatinga', 'laguna', 'dores de campos', 'sao paulo - sp',
       'araras', 'divisa nova', 'igaracu do tiete', 'pitangueiras',
       'campo grande', 'garca', 'presidente epitacio', 'sbc/sp',
       "arraial d'ajuda (porto seguro)", 'pacatuba', 'formosa',
       'borda da mata', 'ubatuba', 'entre rios do oeste', 'formiga',
       'venancio aires', 'navegantes', 'cruzeiro', 'santa maria',
       'muriae', 'santo andre/sao paulo', 'ipe', 'messias targino',
       'varginha', 'botucatu', 'domingos martins', 'uberaba',
       'coronel fabriciano', 'cachoeirinha', 's jose do rio preto',
       'taruma', 'pirassununga', 'aruja', 'sp / sp', 'angra dos reis',
       'juzeiro do norte', 'laurentino', 'flores da cunha', 'montenegro',
       'pedregulho', 'novo hamburgo', 'torres', 'aracaju',
       'santa catarina', 'joao pinheiro', 'bady bassitt', 'sinop',
       'guarapuava', 'araucaria', 'vitoria', 'batatais', 'lagoa santa',
       'chapeco', 'umuarama', 'belford roxo', 'cariacica',
       'monte alegre do sul', 'sp', 'lagoa da prata', 'rolante',
       'teresopolis', 'itaporanga', 'campo largo', 'sao joao de meriti',
       'maua/sao paulo', 'bom jesus dos perdoes', 'brotas', 'irece',
       'coxim', 'jau', 'conselheiro lafaiete', 'amparo',
       'sao miguel do oeste', 'gaspar', 'rio bonito', 'mandaguari',
       'vargem grande paulista', 'conchal', 'cambe', 'marialva',
       'alfenas', 'balneario camboriu', 'palhoca', 'sao bernardo do capo',
       'guara', 'colatina', 'franco da rocha', 'lambari',
       'mogi das cruzes / sp', 'treze tilias',
       'rio de janeiro \\rio de janeiro', 'paulo lopes', 'santa cecilia',
       'braco do norte', 'floresta', 'farroupilha', 'castro', 'luziania',
       'joao monlevade', 'pelotas', 'sao bento', 'campos dos goytacazes',
       'ouro fino', 'sao jose dos pinhas', 'tiete', 'viamao', 'janauba',
       'capivari', 'santa terezinha de itaipu', 'igrejinha',
       'sao bento do sul', 'duque de caxias', 'araxa', 'canoinhas',
       'recife', 'barbacena/ minas gerais', 'vera cruz', 'parnamirim',
       'santo angelo', 'paincandu', 'tres rios', 'tanabi',
       'portoferreira', 'itatiba', 'sarandi', 'cravinhos', 'morrinhos',
       'bebedouro', 'almirante tamandare', 'bertioga', 'natal',
       'belo horizont', 'ivoti', 'andira-pr', 'cerqueira cesar',
       'marapoama', 'imigrante', 'mairinque', 'sao paulo sp',
       'rio de janeiro / rio de janeiro', 'andradas', 'sando andre',
       'nova odessa', 'paulinia', 'extrema', 'olimpia',
       'angra dos reis rj', 'ronda alta', 'sao  paulo', 'sao vicente',
       'pinhais/pr', 'portao', 'registro', 'ao bernardo do campo',
       'carmo do cajuru', 'embu das artes', 'fernando prestes',
       'castro pires', 'vargem grande do sul', 'campina das missoes',
       'sao pedro da aldeia', 'miguelopolis', 'itapui', 'sbc', 'neopolis',
       'mineiros do tiete', 'varzea paulista', 'nova lima', 'barbacena',
       'caieiras', 'buritama', 'erechim', 'itapetininga', 'pinhalzinho',
       'descalvado', 'pitanga', 'bage', 'taio', "santa barbara d'oeste",
       'patos de minas', 'garulhos', 'jarinu', 'nova petropolis',
       'ribeirao preto / sao paulo', 'camboriu', 'nova trento',
       'sao luis', 'sao jose do rio pret', 'eusebio', 'itaipulandia',
       'ipira', 'campo magro', 'tiradentes', 'sao paluo', 'baependi',
       'embu guacu', 'paraiso do sul', 'aparecida', 'cataguases',
       'bariri', 'abadia de goias', 'alambari', 'ji parana', 'vassouras',
       'lorena', 'rodeio', 'louveira', 'guanhaes',
       'santo antonio de padua', 'presidente getulio', 'campos novos',
       'eunapolis', 'engenheiro coelho', 'rio das pedras',
       'afonso claudio', 'carapicuiba / sao paulo', 'centro', 'parana',
       'indaial', 'bombinhas', 'orlandia', 'itapeva', 'sao sebastiao',
       'macatuba', 'sao joao da boa vista', 'teixeira soares',
       'mandaguacu', 'rio do oeste', 'vendas@creditparts.com.br',
       'armacao dos buzios', 'mateus leme', 'sao paulop',
       'campo limpo paulista', 'socorro', 'serra', 'bocaiuva do sul',
       'ilheus', 'imbe', 'soledade', 'cajamar', 'rio negrinho',
       'clementina', 'francisco morato', 'rio grande', 'xaxim', 'manaus',
       'terra boa', 'minas gerais', 'avare', 'ibirite',
       'santa maria da serra', 'auriflama', 'condor', 'ibia', 'guanambi',
       'caucaia', 'cordilheira alta', 'carmo da mata', 'ouro preto',
       'pedro leopoldo', 'santa rosa de viterbo', 'xanxere',
       'alvares machado', 'scao jose do rio pardo', 'ribeirao das neves',
       'medianeira', 'massaranduba', 'cornelio procopio', 'pirituba',
       'jambeiro', 'sao leopoldo', 'aguas claras df', 'ribeirao pretp',
       'cianorte', 'feira de santana', 'cachoeira do sul', 'guariba',
       'sao sebastiao da grama/sp', 'dracena', 'ourinhos',
       'robeirao preto', 'cacador', 'gama', 'queimados', 'cananeia',
       'presidente bernardes', 'pinhalao', 'sombrio', 'campo mourao',
       'ilicinea', 'itabira', 'barrinha', 'jussara', 'uniao da vitoria',
       'triunfo', 'santa cruz do sul', 'colorado', 'itapema', 'sapiranga',
       'paranavai', 'alvorada', 'ipaussu', 'rio verde', 'mage',
       'tabao da serra', 'bofete', 'picarras', 'marica', 'jaragua',
       'governador valadares', 'rio de janeiro, rio de janeiro, brasil',
       'pouso alegre', 'timoteo', 'muqui', 'ipua', 'jacarei / sao paulo',
       'varzea alegre', 'guaratingueta', 'tambau', 'irati',
       'riberao preto', 'aparecida de goiania', 'bandeirantes',
       'vitoria de santo antao', 'palotina', 'leme'], dtype=object)

In [27]:
df['seller_city']=df['seller_city'].replace ({
    'são paulo': 'sao paulo',
    'sao pauo': 'sao paulo',
    'sao paulop': 'sao paulo',
    'sao paulo / sao paulo': 'sao paulo',
    'sao paulo - sp': 'sao paulo',
    'sao  paulo': 'sao paulo',
    'mogi das cruses': 'mogi das cruzes',
    'ferraz de  vasconcelos': 'ferraz de vasconcelos',
    'cascavael': 'cascavel',
    'ribeirao pretp': 'ribeirao preto',
    'rio de janeiro \\rio de janeiro': 'rio de janeiro',
    'rio de janeiro / rio de janeiro': 'rio de janeiro',
    'rio de janeiro, rio de janeiro, brasil': 'rio de janeiro',
    'sbc/sp': 'sao bernardo do campo',
    'sp / sp': 'sao paulo',
    'sao pedro dos pinhas': 'sao jose dos pinhais',
    'balenario camboriu': 'balneario camboriu',
    'são paulo': 'sao paulo',
    'sao bernardo do capo': 'sao bernardo do campo'
})

In [28]:
df['seller_city'].unique()

array(['campinas', 'mogi guacu', 'rio de janeiro', 'sao paulo',
       'braganca paulista', 'brejao', 'penapolis', 'curitiba', 'anapolis',
       'itirapina', 'tubarao', 'lauro de freitas', 'imbituba', 'brasilia',
       'porto seguro', 'guaruja', 'tabatinga', 'salto', 'tres de maio',
       'belo horizonte', 'arapongas', 'sao bernardo do campo', 'tatui',
       'garopaba', 'camanducaia', 'tupa', 'guarulhos',
       'sao jose dos pinhais', 'sao ludgero', 'sao jose', 'piracicaba',
       'porto alegre', 'congonhal', 'santo andre', 'osasco', 'valinhos',
       'joinville', 'saquarema', 'barra velha', 'petropolis',
       'santo antonio da patrulha', 'ponta grossa', 'santana de parnaiba',
       'sao carlos', 'ibitinga', 'barueri', 'caxias do sul', 'araguari',
       'contagem', 'jaragua do sul', 'lages - sc', 'bento goncalves',
       'catanduva', 'ribeirao pires', 'jaboticabal', 'echapora', 'cotia',
       'rio do sul', 'sorocaba', 'pradopolis', 'itaborai', 'mirassol',
       'birigui', 'assis', 'jaguariuna', 'araraquara', 'macae',
       'rio claro', 'londrina', 'ribeirao preto', 'tres coracoes',
       'nhandeara', 'orleans', 'cuiaba', 'formosa do oeste', 'santos',
       'santa terezinha de goias', 'arvorezinha', 'guiricema', 'caruaru',
       'franca', 'salvador', 'diadema', 'itaquaquecetuba',
       'lencois paulista', 'carapicuiba', 'uruacu', 'itajai', 'loanda',
       'maringa', 'ferraz de vasconcelos', 'limeira', 'claudio',
       'niteroi', 'osvaldo cruz', 'sao goncalo', 'jaciara',
       'balneario camboriu', 'timbo', 'jacutinga', 'fortaleza',
       'mirandopolis', 'bauru', 'jacarei', 'itu', 'laranjeiras do sul',
       'videira', 'florianopolis', 'itapecerica da serra', 'mamanguape',
       'ponte nova', 'goioere', 'pederneiras', 'itapevi', 'goiania',
       'campina grande', 'estancia velha', 'resende', 'maua', 'caratinga',
       'auriflama/sp', 'cafelandia', 'uba', 'sao jose do rio preto',
       'porto ferreira', 'tres coroas', 'blumenau', 'mogi das cruzes',
       'jaci', 'laranjal paulista', 'americana', 'sertanopolis',
       'apucarana', 'colombo', 'vicente de carvalho', 'mesquita',
       'cascavel', 'fazenda rio grande', 'taboao da serra',
       'sao jose dos campos', 'toledo', 'marechal candido rondon',
       'jundiai', 'mandirituba', 'suzano', 'vespasiano', 'santa rosa',
       'sao joaquim da barra', 'santo antonio de posse', 'uruguaiana',
       'campanha', 'piracanjuba', 'concordia', 'santa rita do sapucai',
       'barretos', 'indaiatuba', 'nilopolis', 'pompeia', 'barro alto',
       'praia grande', 'luiz alves', 'brusque', 'criciuma', 'jales',
       'atibaia', 'rio branco', 'barra mansa', 'marilia', 'bahia',
       'taubate', 'monteiro lobato', 'viana', 'paraiba do sul', 'mococa',
       'sao roque', 'passos', 'francisco beltrao', 'tocantins',
       'porto belo', 'nova iguacu', 'icara', 'lajeado', 'horizontina',
       'votorantim', 'campo bom', 'monte alto', 'fernandopolis',
       'pedreira', 'poa', 'divinopolis', 'santa barbara d´oeste',
       'canoas', 'mombuca', 'sete lagoas', 'campo do meio',
       'cordeiropolis', 'uberlandia', 'santa barbara d oeste',
       'volta redonda', '04482255', 'aracatuba', 'monte siao', 'garuva',
       'bonfinopolis de minas', 'cosmopolis', 'pocos de caldas',
       'artur nogueira', 'joao pessoa', 'dois corregos', 'araquari',
       'novo hamburgo, rio grande do sul, brasil', 'floranopolis',
       'sumare', 'guaira', 'cachoeiro de itapemirim', 'serrana',
       'rolandia', 'congonhas', 'sao  jose dos pinhais', 'boituva',
       'mairipora', 'guaimbe', 'parai', 'aperibe', 'jaguaruna',
       'vila velha', 'juiz de fora', 'fronteira', 'novo horizonte',
       'pilar do sul', 'itajobi', 'cariacica / es', 'prados', 'mucambo',
       'montes claros', 'vicosa', 'porto velho', 'sao jose do rio pardo',
       'pato branco', 'sao joao del rei', 'presidente prudente',
       'paracambi', 'serra negra', 'sao caetano do sul', 'bom jardim',
       'serra redonda', 'sao francisco do sul', 'betim', 'imbituva',
       'guaratuba', 'teresina', "sao miguel d'oeste", 'california',
       'japira', 'foz do iguacu', 'nova friburgo', 'itau de minas',
       'oliveira', 'sabara', 'pedrinhas paulista', 'votuporanga',
       'holambra', 'ararangua', 'pinhais', 'pato bragado', 'carazinho',
       'arinos', 'sao pedro', 'lages', 'ampere', 'itauna', 'mogi mirim',
       'curitibanos', 'brasilia df', 'hortolandia', 'ipatinga', 'laguna',
       'dores de campos', 'araras', 'divisa nova', 'igaracu do tiete',
       'pitangueiras', 'campo grande', 'garca', 'presidente epitacio',
       "arraial d'ajuda (porto seguro)", 'pacatuba', 'formosa',
       'borda da mata', 'ubatuba', 'entre rios do oeste', 'formiga',
       'venancio aires', 'navegantes', 'cruzeiro', 'santa maria',
       'muriae', 'santo andre/sao paulo', 'ipe', 'messias targino',
       'varginha', 'botucatu', 'domingos martins', 'uberaba',
       'coronel fabriciano', 'cachoeirinha', 's jose do rio preto',
       'taruma', 'pirassununga', 'aruja', 'angra dos reis',
       'juzeiro do norte', 'laurentino', 'flores da cunha', 'montenegro',
       'pedregulho', 'novo hamburgo', 'torres', 'aracaju',
       'santa catarina', 'joao pinheiro', 'bady bassitt', 'sinop',
       'guarapuava', 'araucaria', 'vitoria', 'batatais', 'lagoa santa',
       'chapeco', 'umuarama', 'belford roxo', 'cariacica',
       'monte alegre do sul', 'sp', 'lagoa da prata', 'rolante',
       'teresopolis', 'itaporanga', 'campo largo', 'sao joao de meriti',
       'maua/sao paulo', 'bom jesus dos perdoes', 'brotas', 'irece',
       'coxim', 'jau', 'conselheiro lafaiete', 'amparo',
       'sao miguel do oeste', 'gaspar', 'rio bonito', 'mandaguari',
       'vargem grande paulista', 'conchal', 'cambe', 'marialva',
       'alfenas', 'palhoca', 'guara', 'colatina', 'franco da rocha',
       'lambari', 'mogi das cruzes / sp', 'treze tilias', 'paulo lopes',
       'santa cecilia', 'braco do norte', 'floresta', 'farroupilha',
       'castro', 'luziania', 'joao monlevade', 'pelotas', 'sao bento',
       'campos dos goytacazes', 'ouro fino', 'sao jose dos pinhas',
       'tiete', 'viamao', 'janauba', 'capivari',
       'santa terezinha de itaipu', 'igrejinha', 'sao bento do sul',
       'duque de caxias', 'araxa', 'canoinhas', 'recife',
       'barbacena/ minas gerais', 'vera cruz', 'parnamirim',
       'santo angelo', 'paincandu', 'tres rios', 'tanabi',
       'portoferreira', 'itatiba', 'sarandi', 'cravinhos', 'morrinhos',
       'bebedouro', 'almirante tamandare', 'bertioga', 'natal',
       'belo horizont', 'ivoti', 'andira-pr', 'cerqueira cesar',
       'marapoama', 'imigrante', 'mairinque', 'sao paulo sp', 'andradas',
       'sando andre', 'nova odessa', 'paulinia', 'extrema', 'olimpia',
       'angra dos reis rj', 'ronda alta', 'sao vicente', 'pinhais/pr',
       'portao', 'registro', 'ao bernardo do campo', 'carmo do cajuru',
       'embu das artes', 'fernando prestes', 'castro pires',
       'vargem grande do sul', 'campina das missoes',
       'sao pedro da aldeia', 'miguelopolis', 'itapui', 'sbc', 'neopolis',
       'mineiros do tiete', 'varzea paulista', 'nova lima', 'barbacena',
       'caieiras', 'buritama', 'erechim', 'itapetininga', 'pinhalzinho',
       'descalvado', 'pitanga', 'bage', 'taio', "santa barbara d'oeste",
       'patos de minas', 'garulhos', 'jarinu', 'nova petropolis',
       'ribeirao preto / sao paulo', 'camboriu', 'nova trento',
       'sao luis', 'sao jose do rio pret', 'eusebio', 'itaipulandia',
       'ipira', 'campo magro', 'tiradentes', 'sao paluo', 'baependi',
       'embu guacu', 'paraiso do sul', 'aparecida', 'cataguases',
       'bariri', 'abadia de goias', 'alambari', 'ji parana', 'vassouras',
       'lorena', 'rodeio', 'louveira', 'guanhaes',
       'santo antonio de padua', 'presidente getulio', 'campos novos',
       'eunapolis', 'engenheiro coelho', 'rio das pedras',
       'afonso claudio', 'carapicuiba / sao paulo', 'centro', 'parana',
       'indaial', 'bombinhas', 'orlandia', 'itapeva', 'sao sebastiao',
       'macatuba', 'sao joao da boa vista', 'teixeira soares',
       'mandaguacu', 'rio do oeste', 'vendas@creditparts.com.br',
       'armacao dos buzios', 'mateus leme', 'campo limpo paulista',
       'socorro', 'serra', 'bocaiuva do sul', 'ilheus', 'imbe',
       'soledade', 'cajamar', 'rio negrinho', 'clementina',
       'francisco morato', 'rio grande', 'xaxim', 'manaus', 'terra boa',
       'minas gerais', 'avare', 'ibirite', 'santa maria da serra',
       'auriflama', 'condor', 'ibia', 'guanambi', 'caucaia',
       'cordilheira alta', 'carmo da mata', 'ouro preto',
       'pedro leopoldo', 'santa rosa de viterbo', 'xanxere',
       'alvares machado', 'scao jose do rio pardo', 'ribeirao das neves',
       'medianeira', 'massaranduba', 'cornelio procopio', 'pirituba',
       'jambeiro', 'sao leopoldo', 'aguas claras df', 'cianorte',
       'feira de santana', 'cachoeira do sul', 'guariba',
       'sao sebastiao da grama/sp', 'dracena', 'ourinhos',
       'robeirao preto', 'cacador', 'gama', 'queimados', 'cananeia',
       'presidente bernardes', 'pinhalao', 'sombrio', 'campo mourao',
       'ilicinea', 'itabira', 'barrinha', 'jussara', 'uniao da vitoria',
       'triunfo', 'santa cruz do sul', 'colorado', 'itapema', 'sapiranga',
       'paranavai', 'alvorada', 'ipaussu', 'rio verde', 'mage',
       'tabao da serra', 'bofete', 'picarras', 'marica', 'jaragua',
       'governador valadares', 'pouso alegre', 'timoteo', 'muqui', 'ipua',
       'jacarei / sao paulo', 'varzea alegre', 'guaratingueta', 'tambau',
       'irati', 'riberao preto', 'aparecida de goiania', 'bandeirantes',
       'vitoria de santo antao', 'palotina', 'leme'], dtype=object)

In [30]:
df['seller_city'] = (
    df['seller_city']
    .str.lower()
    .str.strip()
)

In [31]:
#  Remove state info after slash, dash, comma, parentheses
df['seller_city'] = (
    df['seller_city']
    .str.split(r'[/,-]|\\(|\\)', expand=False)
    .str[0]
    .str.strip()
)

In [32]:
#  Remove double spaces
df['seller_city'] = df['seller_city'].str.replace(r'\s+', ' ', regex=True)

In [33]:
#  Remove obvious non-city values
df = df[~df['seller_city'].str.contains(r'@|\d{5,}', regex=True)]

In [34]:
# 5 Fix common typos
replacements = {
    'garulhos': 'guarulhos',
    'robeirao preto': 'ribeirao preto',
    'riberao preto': 'ribeirao preto',
    'sao paluo': 'sao paulo',
    'belo horizont': 'belo horizonte',
    'ao bernardo do campo': 'sao bernardo do campo',
    'scao jose do rio pardo': 'sao jose do rio pardo',
    's jose do rio preto': 'sao jose do rio preto',
    'sao jose do rio pret': 'sao jose do rio preto',
    'sao jose dos pinhas': 'sao jose dos pinhais',
}

df['seller_city'] = df['seller_city'].replace(replacements)

In [35]:
df['seller_city'].unique()

array(['campinas', 'mogi guacu', 'rio de janeiro', 'sao paulo',
       'braganca paulista', 'brejao', 'penapolis', 'curitiba', 'anapolis',
       'itirapina', 'tubarao', 'lauro de freitas', 'imbituba', 'brasilia',
       'porto seguro', 'guaruja', 'tabatinga', 'salto', 'tres de maio',
       'belo horizonte', 'arapongas', 'sao bernardo do campo', 'tatui',
       'garopaba', 'camanducaia', 'tupa', 'guarulhos',
       'sao jose dos pinhais', 'sao ludgero', 'sao jose', 'piracicaba',
       'porto alegre', 'congonhal', 'santo andre', 'osasco', 'valinhos',
       'joinville', 'saquarema', 'barra velha', 'petropolis',
       'santo antonio da patrulha', 'ponta grossa', 'santana de parnaiba',
       'sao carlos', 'ibitinga', 'barueri', 'caxias do sul', 'araguari',
       'contagem', 'jaragua do sul', 'lages', 'bento goncalves',
       'catanduva', 'ribeirao pires', 'jaboticabal', 'echapora', 'cotia',
       'rio do sul', 'sorocaba', 'pradopolis', 'itaborai', 'mirassol',
       'birigui', 'assis', 'jaguariuna', 'araraquara', 'macae',
       'rio claro', 'londrina', 'ribeirao preto', 'tres coracoes',
       'nhandeara', 'orleans', 'cuiaba', 'formosa do oeste', 'santos',
       'santa terezinha de goias', 'arvorezinha', 'guiricema', 'caruaru',
       'franca', 'salvador', 'diadema', 'itaquaquecetuba',
       'lencois paulista', 'carapicuiba', 'uruacu', 'itajai', 'loanda',
       'maringa', 'ferraz de vasconcelos', 'limeira', 'claudio',
       'niteroi', 'osvaldo cruz', 'sao goncalo', 'jaciara',
       'balneario camboriu', 'timbo', 'jacutinga', 'fortaleza',
       'mirandopolis', 'bauru', 'jacarei', 'itu', 'laranjeiras do sul',
       'videira', 'florianopolis', 'itapecerica da serra', 'mamanguape',
       'ponte nova', 'goioere', 'pederneiras', 'itapevi', 'goiania',
       'campina grande', 'estancia velha', 'resende', 'maua', 'caratinga',
       'auriflama', 'cafelandia', 'uba', 'sao jose do rio preto',
       'porto ferreira', 'tres coroas', 'blumenau', 'mogi das cruzes',
       'jaci', 'laranjal paulista', 'americana', 'sertanopolis',
       'apucarana', 'colombo', 'vicente de carvalho', 'mesquita',
       'cascavel', 'fazenda rio grande', 'taboao da serra',
       'sao jose dos campos', 'toledo', 'marechal candido rondon',
       'jundiai', 'mandirituba', 'suzano', 'vespasiano', 'santa rosa',
       'sao joaquim da barra', 'santo antonio de posse', 'uruguaiana',
       'campanha', 'piracanjuba', 'concordia', 'santa rita do sapucai',
       'barretos', 'indaiatuba', 'nilopolis', 'pompeia', 'barro alto',
       'praia grande', 'luiz alves', 'brusque', 'criciuma', 'jales',
       'atibaia', 'rio branco', 'barra mansa', 'marilia', 'bahia',
       'taubate', 'monteiro lobato', 'viana', 'paraiba do sul', 'mococa',
       'sao roque', 'passos', 'francisco beltrao', 'tocantins',
       'porto belo', 'nova iguacu', 'icara', 'lajeado', 'horizontina',
       'votorantim', 'campo bom', 'monte alto', 'fernandopolis',
       'pedreira', 'poa', 'divinopolis', 'santa barbara d´oeste',
       'canoas', 'mombuca', 'sete lagoas', 'campo do meio',
       'cordeiropolis', 'uberlandia', 'santa barbara d oeste',
       'volta redonda', 'aracatuba', 'monte siao', 'garuva',
       'bonfinopolis de minas', 'cosmopolis', 'pocos de caldas',
       'artur nogueira', 'joao pessoa', 'dois corregos', 'araquari',
       'novo hamburgo', 'floranopolis', 'sumare', 'guaira',
       'cachoeiro de itapemirim', 'serrana', 'rolandia', 'congonhas',
       'boituva', 'mairipora', 'guaimbe', 'parai', 'aperibe', 'jaguaruna',
       'vila velha', 'juiz de fora', 'fronteira', 'novo horizonte',
       'pilar do sul', 'itajobi', 'cariacica', 'prados', 'mucambo',
       'montes claros', 'vicosa', 'porto velho', 'sao jose do rio pardo',
       'pato branco', 'sao joao del rei', 'presidente prudente',
       'paracambi', 'serra negra', 'sao caetano do sul', 'bom jardim',
       'serra redonda', 'sao francisco do sul', 'betim', 'imbituva',
       'guaratuba', 'teresina', "sao miguel d'oeste", 'california',
       'japira', 'foz do iguacu', 'nova friburgo', 'itau de minas',
       'oliveira', 'sabara', 'pedrinhas paulista', 'votuporanga',
       'holambra', 'ararangua', 'pinhais', 'pato bragado', 'carazinho',
       'arinos', 'sao pedro', 'ampere', 'itauna', 'mogi mirim',
       'curitibanos', 'brasilia df', 'hortolandia', 'ipatinga', 'laguna',
       'dores de campos', 'araras', 'divisa nova', 'igaracu do tiete',
       'pitangueiras', 'campo grande', 'garca', 'presidente epitacio',
       "arraial d'ajuda (porto seguro)", 'pacatuba', 'formosa',
       'borda da mata', 'ubatuba', 'entre rios do oeste', 'formiga',
       'venancio aires', 'navegantes', 'cruzeiro', 'santa maria',
       'muriae', 'ipe', 'messias targino', 'varginha', 'botucatu',
       'domingos martins', 'uberaba', 'coronel fabriciano',
       'cachoeirinha', 'taruma', 'pirassununga', 'aruja',
       'angra dos reis', 'juzeiro do norte', 'laurentino',
       'flores da cunha', 'montenegro', 'pedregulho', 'torres', 'aracaju',
       'santa catarina', 'joao pinheiro', 'bady bassitt', 'sinop',
       'guarapuava', 'araucaria', 'vitoria', 'batatais', 'lagoa santa',
       'chapeco', 'umuarama', 'belford roxo', 'monte alegre do sul', 'sp',
       'lagoa da prata', 'rolante', 'teresopolis', 'itaporanga',
       'campo largo', 'sao joao de meriti', 'bom jesus dos perdoes',
       'brotas', 'irece', 'coxim', 'jau', 'conselheiro lafaiete',
       'amparo', 'sao miguel do oeste', 'gaspar', 'rio bonito',
       'mandaguari', 'vargem grande paulista', 'conchal', 'cambe',
       'marialva', 'alfenas', 'palhoca', 'guara', 'colatina',
       'franco da rocha', 'lambari', 'treze tilias', 'paulo lopes',
       'santa cecilia', 'braco do norte', 'floresta', 'farroupilha',
       'castro', 'luziania', 'joao monlevade', 'pelotas', 'sao bento',
       'campos dos goytacazes', 'ouro fino', 'tiete', 'viamao', 'janauba',
       'capivari', 'santa terezinha de itaipu', 'igrejinha',
       'sao bento do sul', 'duque de caxias', 'araxa', 'canoinhas',
       'recife', 'barbacena', 'vera cruz', 'parnamirim', 'santo angelo',
       'paincandu', 'tres rios', 'tanabi', 'portoferreira', 'itatiba',
       'sarandi', 'cravinhos', 'morrinhos', 'bebedouro',
       'almirante tamandare', 'bertioga', 'natal', 'ivoti', 'andira',
       'cerqueira cesar', 'marapoama', 'imigrante', 'mairinque',
       'sao paulo sp', 'andradas', 'sando andre', 'nova odessa',
       'paulinia', 'extrema', 'olimpia', 'angra dos reis rj',
       'ronda alta', 'sao vicente', 'portao', 'registro',
       'carmo do cajuru', 'embu das artes', 'fernando prestes',
       'castro pires', 'vargem grande do sul', 'campina das missoes',
       'sao pedro da aldeia', 'miguelopolis', 'itapui', 'sbc', 'neopolis',
       'mineiros do tiete', 'varzea paulista', 'nova lima', 'caieiras',
       'buritama', 'erechim', 'itapetininga', 'pinhalzinho', 'descalvado',
       'pitanga', 'bage', 'taio', "santa barbara d'oeste",
       'patos de minas', 'jarinu', 'nova petropolis', 'camboriu',
       'nova trento', 'sao luis', 'eusebio', 'itaipulandia', 'ipira',
       'campo magro', 'tiradentes', 'baependi', 'embu guacu',
       'paraiso do sul', 'aparecida', 'cataguases', 'bariri',
       'abadia de goias', 'alambari', 'ji parana', 'vassouras', 'lorena',
       'rodeio', 'louveira', 'guanhaes', 'santo antonio de padua',
       'presidente getulio', 'campos novos', 'eunapolis',
       'engenheiro coelho', 'rio das pedras', 'afonso claudio', 'centro',
       'parana', 'indaial', 'bombinhas', 'orlandia', 'itapeva',
       'sao sebastiao', 'macatuba', 'sao joao da boa vista',
       'teixeira soares', 'mandaguacu', 'rio do oeste',
       'armacao dos buzios', 'mateus leme', 'campo limpo paulista',
       'socorro', 'serra', 'bocaiuva do sul', 'ilheus', 'imbe',
       'soledade', 'cajamar', 'rio negrinho', 'clementina',
       'francisco morato', 'rio grande', 'xaxim', 'manaus', 'terra boa',
       'minas gerais', 'avare', 'ibirite', 'santa maria da serra',
       'condor', 'ibia', 'guanambi', 'caucaia', 'cordilheira alta',
       'carmo da mata', 'ouro preto', 'pedro leopoldo',
       'santa rosa de viterbo', 'xanxere', 'alvares machado',
       'ribeirao das neves', 'medianeira', 'massaranduba',
       'cornelio procopio', 'pirituba', 'jambeiro', 'sao leopoldo',
       'aguas claras df', 'cianorte', 'feira de santana',
       'cachoeira do sul', 'guariba', 'sao sebastiao da grama', 'dracena',
       'ourinhos', 'cacador', 'gama', 'queimados', 'cananeia',
       'presidente bernardes', 'pinhalao', 'sombrio', 'campo mourao',
       'ilicinea', 'itabira', 'barrinha', 'jussara', 'uniao da vitoria',
       'triunfo', 'santa cruz do sul', 'colorado', 'itapema', 'sapiranga',
       'paranavai', 'alvorada', 'ipaussu', 'rio verde', 'mage',
       'tabao da serra', 'bofete', 'picarras', 'marica', 'jaragua',
       'governador valadares', 'pouso alegre', 'timoteo', 'muqui', 'ipua',
       'varzea alegre', 'guaratingueta', 'tambau', 'irati',
       'aparecida de goiania', 'bandeirantes', 'vitoria de santo antao',
       'palotina', 'leme'], dtype=object)

In [36]:
# Remove state-only entries
states = ['bahia', 'tocantins', 'santa catarina', 'parana', 'minas gerais', 'sp']
df = df[~df['seller_city'].isin(states)].copy()

# Remove state suffixes
df['seller_city'] = (
    df['seller_city']
    .str.replace(r'\s+(sp|rj|df)$', '', regex=True)
)

# Fix remaining typos
final_replacements = {
    'floranopolis': 'florianopolis',
    'sando andre': 'santo andre',
    'portoferreira': 'porto ferreira',
    'sbc': 'sao bernardo do campo',
    'centro': None,
    "santa barbara d´oeste": "santa barbara d'oeste"
}

df['seller_city'] = df['seller_city'].replace(final_replacements)

# Drop None values
df = df.dropna(subset=['seller_city'])

In [37]:
df['seller_city'].unique()

array(['campinas', 'mogi guacu', 'rio de janeiro', 'sao paulo',
       'braganca paulista', 'brejao', 'penapolis', 'curitiba', 'anapolis',
       'itirapina', 'tubarao', 'lauro de freitas', 'imbituba', 'brasilia',
       'porto seguro', 'guaruja', 'tabatinga', 'salto', 'tres de maio',
       'belo horizonte', 'arapongas', 'sao bernardo do campo', 'tatui',
       'garopaba', 'camanducaia', 'tupa', 'guarulhos',
       'sao jose dos pinhais', 'sao ludgero', 'sao jose', 'piracicaba',
       'porto alegre', 'congonhal', 'santo andre', 'osasco', 'valinhos',
       'joinville', 'saquarema', 'barra velha', 'petropolis',
       'santo antonio da patrulha', 'ponta grossa', 'santana de parnaiba',
       'sao carlos', 'ibitinga', 'barueri', 'caxias do sul', 'araguari',
       'contagem', 'jaragua do sul', 'lages', 'bento goncalves',
       'catanduva', 'ribeirao pires', 'jaboticabal', 'echapora', 'cotia',
       'rio do sul', 'sorocaba', 'pradopolis', 'itaborai', 'mirassol',
       'birigui', 'assis', 'jaguariuna', 'araraquara', 'macae',
       'rio claro', 'londrina', 'ribeirao preto', 'tres coracoes',
       'nhandeara', 'orleans', 'cuiaba', 'formosa do oeste', 'santos',
       'santa terezinha de goias', 'arvorezinha', 'guiricema', 'caruaru',
       'franca', 'salvador', 'diadema', 'itaquaquecetuba',
       'lencois paulista', 'carapicuiba', 'uruacu', 'itajai', 'loanda',
       'maringa', 'ferraz de vasconcelos', 'limeira', 'claudio',
       'niteroi', 'osvaldo cruz', 'sao goncalo', 'jaciara',
       'balneario camboriu', 'timbo', 'jacutinga', 'fortaleza',
       'mirandopolis', 'bauru', 'jacarei', 'itu', 'laranjeiras do sul',
       'videira', 'florianopolis', 'itapecerica da serra', 'mamanguape',
       'ponte nova', 'goioere', 'pederneiras', 'itapevi', 'goiania',
       'campina grande', 'estancia velha', 'resende', 'maua', 'caratinga',
       'auriflama', 'cafelandia', 'uba', 'sao jose do rio preto',
       'porto ferreira', 'tres coroas', 'blumenau', 'mogi das cruzes',
       'jaci', 'laranjal paulista', 'americana', 'sertanopolis',
       'apucarana', 'colombo', 'vicente de carvalho', 'mesquita',
       'cascavel', 'fazenda rio grande', 'taboao da serra',
       'sao jose dos campos', 'toledo', 'marechal candido rondon',
       'jundiai', 'mandirituba', 'suzano', 'vespasiano', 'santa rosa',
       'sao joaquim da barra', 'santo antonio de posse', 'uruguaiana',
       'campanha', 'piracanjuba', 'concordia', 'santa rita do sapucai',
       'barretos', 'indaiatuba', 'nilopolis', 'pompeia', 'barro alto',
       'praia grande', 'luiz alves', 'brusque', 'criciuma', 'jales',
       'atibaia', 'rio branco', 'barra mansa', 'marilia', 'taubate',
       'monteiro lobato', 'viana', 'paraiba do sul', 'mococa',
       'sao roque', 'passos', 'francisco beltrao', 'porto belo',
       'nova iguacu', 'icara', 'lajeado', 'horizontina', 'votorantim',
       'campo bom', 'monte alto', 'fernandopolis', 'pedreira', 'poa',
       'divinopolis', "santa barbara d'oeste", 'canoas', 'mombuca',
       'sete lagoas', 'campo do meio', 'cordeiropolis', 'uberlandia',
       'santa barbara d oeste', 'volta redonda', 'aracatuba',
       'monte siao', 'garuva', 'bonfinopolis de minas', 'cosmopolis',
       'pocos de caldas', 'artur nogueira', 'joao pessoa',
       'dois corregos', 'araquari', 'novo hamburgo', 'sumare', 'guaira',
       'cachoeiro de itapemirim', 'serrana', 'rolandia', 'congonhas',
       'boituva', 'mairipora', 'guaimbe', 'parai', 'aperibe', 'jaguaruna',
       'vila velha', 'juiz de fora', 'fronteira', 'novo horizonte',
       'pilar do sul', 'itajobi', 'cariacica', 'prados', 'mucambo',
       'montes claros', 'vicosa', 'porto velho', 'sao jose do rio pardo',
       'pato branco', 'sao joao del rei', 'presidente prudente',
       'paracambi', 'serra negra', 'sao caetano do sul', 'bom jardim',
       'serra redonda', 'sao francisco do sul', 'betim', 'imbituva',
       'guaratuba', 'teresina', "sao miguel d'oeste", 'california',
       'japira', 'foz do iguacu', 'nova friburgo', 'itau de minas',
       'oliveira', 'sabara', 'pedrinhas paulista', 'votuporanga',
       'holambra', 'ararangua', 'pinhais', 'pato bragado', 'carazinho',
       'arinos', 'sao pedro', 'ampere', 'itauna', 'mogi mirim',
       'curitibanos', 'hortolandia', 'ipatinga', 'laguna',
       'dores de campos', 'araras', 'divisa nova', 'igaracu do tiete',
       'pitangueiras', 'campo grande', 'garca', 'presidente epitacio',
       "arraial d'ajuda (porto seguro)", 'pacatuba', 'formosa',
       'borda da mata', 'ubatuba', 'entre rios do oeste', 'formiga',
       'venancio aires', 'navegantes', 'cruzeiro', 'santa maria',
       'muriae', 'ipe', 'messias targino', 'varginha', 'botucatu',
       'domingos martins', 'uberaba', 'coronel fabriciano',
       'cachoeirinha', 'taruma', 'pirassununga', 'aruja',
       'angra dos reis', 'juzeiro do norte', 'laurentino',
       'flores da cunha', 'montenegro', 'pedregulho', 'torres', 'aracaju',
       'joao pinheiro', 'bady bassitt', 'sinop', 'guarapuava',
       'araucaria', 'vitoria', 'batatais', 'lagoa santa', 'chapeco',
       'umuarama', 'belford roxo', 'monte alegre do sul',
       'lagoa da prata', 'rolante', 'teresopolis', 'itaporanga',
       'campo largo', 'sao joao de meriti', 'bom jesus dos perdoes',
       'brotas', 'irece', 'coxim', 'jau', 'conselheiro lafaiete',
       'amparo', 'sao miguel do oeste', 'gaspar', 'rio bonito',
       'mandaguari', 'vargem grande paulista', 'conchal', 'cambe',
       'marialva', 'alfenas', 'palhoca', 'guara', 'colatina',
       'franco da rocha', 'lambari', 'treze tilias', 'paulo lopes',
       'santa cecilia', 'braco do norte', 'floresta', 'farroupilha',
       'castro', 'luziania', 'joao monlevade', 'pelotas', 'sao bento',
       'campos dos goytacazes', 'ouro fino', 'tiete', 'viamao', 'janauba',
       'capivari', 'santa terezinha de itaipu', 'igrejinha',
       'sao bento do sul', 'duque de caxias', 'araxa', 'canoinhas',
       'recife', 'barbacena', 'vera cruz', 'parnamirim', 'santo angelo',
       'paincandu', 'tres rios', 'tanabi', 'itatiba', 'sarandi',
       'cravinhos', 'morrinhos', 'bebedouro', 'almirante tamandare',
       'bertioga', 'natal', 'ivoti', 'andira', 'cerqueira cesar',
       'marapoama', 'imigrante', 'mairinque', 'andradas', 'nova odessa',
       'paulinia', 'extrema', 'olimpia', 'ronda alta', 'sao vicente',
       'portao', 'registro', 'carmo do cajuru', 'embu das artes',
       'fernando prestes', 'castro pires', 'vargem grande do sul',
       'campina das missoes', 'sao pedro da aldeia', 'miguelopolis',
       'itapui', 'neopolis', 'mineiros do tiete', 'varzea paulista',
       'nova lima', 'caieiras', 'buritama', 'erechim', 'itapetininga',
       'pinhalzinho', 'descalvado', 'pitanga', 'bage', 'taio',
       'patos de minas', 'jarinu', 'nova petropolis', 'camboriu',
       'nova trento', 'sao luis', 'eusebio', 'itaipulandia', 'ipira',
       'campo magro', 'tiradentes', 'baependi', 'embu guacu',
       'paraiso do sul', 'aparecida', 'cataguases', 'bariri',
       'abadia de goias', 'alambari', 'ji parana', 'vassouras', 'lorena',
       'rodeio', 'louveira', 'guanhaes', 'santo antonio de padua',
       'presidente getulio', 'campos novos', 'eunapolis',
       'engenheiro coelho', 'rio das pedras', 'afonso claudio', 'indaial',
       'bombinhas', 'orlandia', 'itapeva', 'sao sebastiao', 'macatuba',
       'sao joao da boa vista', 'teixeira soares', 'mandaguacu',
       'rio do oeste', 'armacao dos buzios', 'mateus leme',
       'campo limpo paulista', 'socorro', 'serra', 'bocaiuva do sul',
       'ilheus', 'imbe', 'soledade', 'cajamar', 'rio negrinho',
       'clementina', 'francisco morato', 'rio grande', 'xaxim', 'manaus',
       'terra boa', 'avare', 'ibirite', 'santa maria da serra', 'condor',
       'ibia', 'guanambi', 'caucaia', 'cordilheira alta', 'carmo da mata',
       'ouro preto', 'pedro leopoldo', 'santa rosa de viterbo', 'xanxere',
       'alvares machado', 'ribeirao das neves', 'medianeira',
       'massaranduba', 'cornelio procopio', 'pirituba', 'jambeiro',
       'sao leopoldo', 'aguas claras', 'cianorte', 'feira de santana',
       'cachoeira do sul', 'guariba', 'sao sebastiao da grama', 'dracena',
       'ourinhos', 'cacador', 'gama', 'queimados', 'cananeia',
       'presidente bernardes', 'pinhalao', 'sombrio', 'campo mourao',
       'ilicinea', 'itabira', 'barrinha', 'jussara', 'uniao da vitoria',
       'triunfo', 'santa cruz do sul', 'colorado', 'itapema', 'sapiranga',
       'paranavai', 'alvorada', 'ipaussu', 'rio verde', 'mage',
       'tabao da serra', 'bofete', 'picarras', 'marica', 'jaragua',
       'governador valadares', 'pouso alegre', 'timoteo', 'muqui', 'ipua',
       'varzea alegre', 'guaratingueta', 'tambau', 'irati',
       'aparecida de goiania', 'bandeirantes', 'vitoria de santo antao',
       'palotina', 'leme'], dtype=object)

In [38]:
df['seller_city'] = df['seller_city'].str.replace(" d oeste", " d'oeste")

In [39]:
df['seller_city'] = df['seller_city'].replace(
    {"arraial d'ajuda (porto seguro)": "porto seguro"}
)

In [41]:
df.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [43]:
df.columns

Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='object')

In [48]:
df.to_csv(r"C:\Users\gadis\Downloads\olist\Clean Datasets\sellers.csv",index=False, lineterminator="\n")

In [47]:
df1 = pd.read_csv(r"C:\Users\gadis\Downloads\olist\product_category_name_translation.csv")

In [50]:
df1

            product_category_name product_category_name_english
0                    beleza_saude                 health_beauty
1          informatica_acessorios         computers_accessories
2                      automotivo                          auto
3                 cama_mesa_banho                bed_bath_table
4                moveis_decoracao               furniture_decor
..                            ...                           ...
66                         flores                       flowers
67             artes_e_artesanato         arts_and_craftmanship
68                fraldas_higiene           diapers_and_hygiene
69  fashion_roupa_infanto_juvenil     fashion_childrens_clothes
70             seguros_e_servicos         security_and_services

[71 rows x 2 columns]

In [51]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

In [52]:
df1.shape

(71, 2)

In [53]:
df1.describe()

       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

In [54]:
df1.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [55]:
df1.duplicated().sum()

np.int64(0)

In [56]:
df1['product_category_name'].unique()

array(['beleza_saude', 'informatica_acessorios', 'automotivo',
       'cama_mesa_banho', 'moveis_decoracao', 'esporte_lazer',
       'perfumaria', 'utilidades_domesticas', 'telefonia',
       'relogios_presentes', 'alimentos_bebidas', 'bebes', 'papelaria',
       'tablets_impressao_imagem', 'brinquedos', 'telefonia_fixa',
       'ferramentas_jardim', 'fashion_bolsas_e_acessorios',
       'eletroportateis', 'consoles_games', 'audio', 'fashion_calcados',
       'cool_stuff', 'malas_acessorios', 'climatizacao',
       'construcao_ferramentas_construcao',
       'moveis_cozinha_area_de_servico_jantar_e_jardim',
       'construcao_ferramentas_jardim', 'fashion_roupa_masculina',
       'pet_shop', 'moveis_escritorio', 'market_place', 'eletronicos',
       'eletrodomesticos', 'artigos_de_festas', 'casa_conforto',
       'construcao_ferramentas_ferramentas', 'agro_industria_e_comercio',
       'moveis_colchao_e_estofado', 'livros_tecnicos', 'casa_construcao',
       'instrumentos_musicais', 'moveis_sala',
       'construcao_ferramentas_iluminacao',
       'industria_comercio_e_negocios', 'alimentos', 'artes',
       'moveis_quarto', 'livros_interesse_geral',
       'construcao_ferramentas_seguranca',
       'fashion_underwear_e_moda_praia', 'fashion_esporte',
       'sinalizacao_e_seguranca', 'pcs', 'artigos_de_natal',
       'fashion_roupa_feminina', 'eletrodomesticos_2',
       'livros_importados', 'bebidas', 'cine_foto', 'la_cuisine',
       'musica', 'casa_conforto_2', 'portateis_casa_forno_e_cafe',
       'cds_dvds_musicais', 'dvds_blu_ray', 'flores',
       'artes_e_artesanato', 'fraldas_higiene',
       'fashion_roupa_infanto_juvenil', 'seguros_e_servicos'],
      dtype=object)

In [57]:
category_replacements = {
    # merge duplicates
    'eletrodomesticos_2': 'eletrodomesticos',
    'casa_conforto_2': 'casa_conforto',

    # merge construction
    'construcao_ferramentas_construcao': 'construcao_ferramentas',
    'construcao_ferramentas_jardim': 'construcao_ferramentas',
    'construcao_ferramentas_ferramentas': 'construcao_ferramentas',
    'construcao_ferramentas_iluminacao': 'construcao_ferramentas',
    'construcao_ferramentas_seguranca': 'construcao_ferramentas',

    # merge food
    'bebidas': 'alimentos_bebidas',
    'alimentos': 'alimentos_bebidas',

    # merge music media
    'cds_dvds_musicais': 'musica',
    'dvds_blu_ray': 'cine_foto',

    # merge pcs
    'pcs': 'informatica_acessorios'
}

df1['product_category_name'] = df1['product_category_name'].replace(category_replacements)

In [58]:
df1['product_category_name_english'].unique()

array(['health_beauty', 'computers_accessories', 'auto', 'bed_bath_table',
       'furniture_decor', 'sports_leisure', 'perfumery', 'housewares',
       'telephony', 'watches_gifts', 'food_drink', 'baby', 'stationery',
       'tablets_printing_image', 'toys', 'fixed_telephony',
       'garden_tools', 'fashion_bags_accessories', 'small_appliances',
       'consoles_games', 'audio', 'fashion_shoes', 'cool_stuff',
       'luggage_accessories', 'air_conditioning',
       'construction_tools_construction',
       'kitchen_dining_laundry_garden_furniture',
       'costruction_tools_garden', 'fashion_male_clothing', 'pet_shop',
       'office_furniture', 'market_place', 'electronics',
       'home_appliances', 'party_supplies', 'home_confort',
       'costruction_tools_tools', 'agro_industry_and_commerce',
       'furniture_mattress_and_upholstery', 'books_technical',
       'home_construction', 'musical_instruments',
       'furniture_living_room', 'construction_tools_lights',
       'industry_commerce_and_business', 'food', 'art',
       'furniture_bedroom', 'books_general_interest',
       'construction_tools_safety', 'fashion_underwear_beach',
       'fashion_sport', 'signaling_and_security', 'computers',
       'christmas_supplies', 'fashio_female_clothing',
       'home_appliances_2', 'books_imported', 'drinks', 'cine_photo',
       'la_cuisine', 'music', 'home_comfort_2',
       'small_appliances_home_oven_and_coffee', 'cds_dvds_musicals',
       'dvds_blu_ray', 'flowers', 'arts_and_craftmanship',
       'diapers_and_hygiene', 'fashion_childrens_clothes',
       'security_and_services'], dtype=object)

In [59]:
category_replacements = {

    # Fix typos
    'costruction_tools_garden': 'construction_tools_garden',
    'costruction_tools_tools': 'construction_tools_tools',
    'fashio_female_clothing': 'fashion_female_clothing',
    'home_confort': 'home_comfort',

    # Merge duplicates
    'home_appliances_2': 'home_appliances',
    'home_comfort_2': 'home_comfort',

    # Merge food
    'food': 'food_drink',
    'drinks': 'food_drink',

    # Merge construction into one
    'construction_tools_construction': 'construction_tools',
    'construction_tools_garden': 'construction_tools',
    'construction_tools_tools': 'construction_tools',
    'construction_tools_lights': 'construction_tools',
    'construction_tools_safety': 'construction_tools',
    'home_construction': 'construction_tools',

    # Merge media
    'cds_dvds_musicals': 'music',
    'dvds_blu_ray': 'cine_photo',

    # Merge computers
    'computers': 'computers_accessories'
}

df1['product_category_name_english'] = df1['product_category_name_english'].replace(category_replacements)

In [60]:
df1['product_category_name_english'].unique()

array(['health_beauty', 'computers_accessories', 'auto', 'bed_bath_table',
       'furniture_decor', 'sports_leisure', 'perfumery', 'housewares',
       'telephony', 'watches_gifts', 'food_drink', 'baby', 'stationery',
       'tablets_printing_image', 'toys', 'fixed_telephony',
       'garden_tools', 'fashion_bags_accessories', 'small_appliances',
       'consoles_games', 'audio', 'fashion_shoes', 'cool_stuff',
       'luggage_accessories', 'air_conditioning', 'construction_tools',
       'kitchen_dining_laundry_garden_furniture',
       'construction_tools_garden', 'fashion_male_clothing', 'pet_shop',
       'office_furniture', 'market_place', 'electronics',
       'home_appliances', 'party_supplies', 'home_comfort',
       'construction_tools_tools', 'agro_industry_and_commerce',
       'furniture_mattress_and_upholstery', 'books_technical',
       'musical_instruments', 'furniture_living_room',
       'industry_commerce_and_business', 'art', 'furniture_bedroom',
       'books_general_interest', 'fashion_underwear_beach',
       'fashion_sport', 'signaling_and_security', 'christmas_supplies',
       'fashion_female_clothing', 'books_imported', 'cine_photo',
       'la_cuisine', 'music', 'small_appliances_home_oven_and_coffee',
       'flowers', 'arts_and_craftmanship', 'diapers_and_hygiene',
       'fashion_childrens_clothes', 'security_and_services'], dtype=object)

In [61]:
df1['product_category_name_english'] = df1['product_category_name_english'].replace({
    'construction_tools_garden': 'construction_tools',
    'construction_tools_tools': 'construction_tools'
})

In [62]:
df1['product_category_name_english'] = df1['product_category_name_english'].replace({
    'small_appliances_home_oven_and_coffee': 'small_appliances'
})

In [63]:
furniture_map = {
    'furniture_living_room': 'furniture',
    'furniture_bedroom': 'furniture',
    'furniture_mattress_and_upholstery': 'furniture',
    'office_furniture': 'furniture',
    'kitchen_dining_laundry_garden_furniture': 'furniture',
    'furniture_decor': 'furniture'
}

df1['product_category_name_english'] = df1['product_category_name_english'].replace(furniture_map)

In [64]:
df1

            product_category_name product_category_name_english
0                    beleza_saude                 health_beauty
1          informatica_acessorios         computers_accessories
2                      automotivo                          auto
3                 cama_mesa_banho                bed_bath_table
4                moveis_decoracao                     furniture
..                            ...                           ...
66                         flores                       flowers
67             artes_e_artesanato         arts_and_craftmanship
68                fraldas_higiene           diapers_and_hygiene
69  fashion_roupa_infanto_juvenil     fashion_childrens_clothes
70             seguros_e_servicos         security_and_services

[71 rows x 2 columns]

In [65]:
df1.to_csv(r"C:\Users\gadis\Downloads\olist\Clean Datasets\category.csv",index=False, lineterminator="\n")

In [51]:
df2 = pd.read_csv(r"C:\Users\gadis\Downloads\olist\olist_products_dataset.csv")

In [52]:
df2.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

In [67]:
df2['product_category_name'].unique()

array(['perfumaria', 'artes', 'esporte_lazer', 'bebes',
       'utilidades_domesticas', 'instrumentos_musicais', 'cool_stuff',
       'moveis_decoracao', 'eletrodomesticos', 'brinquedos',
       'cama_mesa_banho', 'construcao_ferramentas_seguranca',
       'informatica_acessorios', 'beleza_saude', 'malas_acessorios',
       'ferramentas_jardim', 'moveis_escritorio', 'automotivo',
       'eletronicos', 'fashion_calcados', 'telefonia', 'papelaria',
       'fashion_bolsas_e_acessorios', 'pcs', 'casa_construcao',
       'relogios_presentes', 'construcao_ferramentas_construcao',
       'pet_shop', 'eletroportateis', 'agro_industria_e_comercio', nan,
       'moveis_sala', 'sinalizacao_e_seguranca', 'climatizacao',
       'consoles_games', 'livros_interesse_geral',
       'construcao_ferramentas_ferramentas',
       'fashion_underwear_e_moda_praia', 'fashion_roupa_masculina',
       'moveis_cozinha_area_de_servico_jantar_e_jardim',
       'industria_comercio_e_negocios', 'telefonia_fixa',
       'construcao_ferramentas_iluminacao', 'livros_tecnicos',
       'eletrodomesticos_2', 'artigos_de_festas', 'bebidas',
       'market_place', 'la_cuisine', 'construcao_ferramentas_jardim',
       'fashion_roupa_feminina', 'casa_conforto', 'audio',
       'alimentos_bebidas', 'musica', 'alimentos',
       'tablets_impressao_imagem', 'livros_importados',
       'portateis_casa_forno_e_cafe', 'fashion_esporte',
       'artigos_de_natal', 'fashion_roupa_infanto_juvenil',
       'dvds_blu_ray', 'artes_e_artesanato', 'pc_gamer', 'moveis_quarto',
       'cine_foto', 'fraldas_higiene', 'flores', 'casa_conforto_2',
       'portateis_cozinha_e_preparadores_de_alimentos',
       'seguros_e_servicos', 'moveis_colchao_e_estofado',
       'cds_dvds_musicais'], dtype=object)

In [68]:
# Mapping dictionary from Portuguese to English
category_mapping = {
    'perfumaria': 'perfumery',
    'artes': 'arts',
    'esporte_lazer': 'sports_leisure',
    'bebes': 'babies',
    'utilidades_domesticas': 'home_utilities',
    'instrumentos_musicais': 'musical_instruments',
    'cool_stuff': 'cool_stuff',
    'moveis_decoracao': 'furniture_decor',
    'eletrodomesticos': 'appliances',
    'brinquedos': 'toys',
    'cama_mesa_banho': 'bed_bath_table',
    'construcao_ferramentas_seguranca': 'construction_tools_safety',
    'informatica_acessorios': 'computer_accessories',
    'beleza_saude': 'beauty_health',
    'malas_acessorios': 'bags_accessories',
    'ferramentas_jardim': 'garden_tools',
    'moveis_escritorio': 'office_furniture',
    'automotivo': 'automotive',
    'eletronicos': 'electronics',
    'fashion_calcados': 'fashion_footwear',
    'telefonia': 'telephony',
    'papelaria': 'stationery',
    'fashion_bolsas_e_acessorios': 'fashion_bags_accessories',
    'pcs': 'pcs',
    'casa_construcao': 'home_construction',
    'relogios_presentes': 'watches_gifts',
    'construcao_ferramentas_construcao': 'construction_tools_building',
    'pet_shop': 'pet_shop',
    'eletroportateis': 'portable_appliances',
    'agro_industria_e_comercio': 'agriculture_industry_commerce',
    float('nan'): 'unknown',  # handles NaN values
    'moveis_sala': 'living_room_furniture',
    'sinalizacao_e_seguranca': 'signage_safety',
    'climatizacao': 'air_conditioning',
    'consoles_games': 'game_consoles',
    'livros_interesse_geral': 'books_general_interest',
    'construcao_ferramentas_ferramentas': 'construction_tools_tools',
    'fashion_underwear_e_moda_praia': 'fashion_underwear_beachwear',
    'fashion_roupa_masculina': 'fashion_menswear',
    'moveis_cozinha_area_de_servico_jantar_e_jardim': 'kitchen_dining_garden_furniture',
    'industria_comercio_e_negocios': 'industry_commerce_business',
    'telefonia_fixa': 'landline_phones',
    'construcao_ferramentas_iluminacao': 'construction_tools_lighting',
    'livros_tecnicos': 'technical_books',
    'eletrodomesticos_2': 'appliances',
    'artigos_de_festas': 'party_supplies',
    'bebidas': 'drinks',
    'market_place': 'marketplace',
    'la_cuisine': 'kitchen_appliances',
    'construcao_ferramentas_jardim': 'construction_tools_garden',
    'fashion_roupa_feminina': 'fashion_womenswear',
    'casa_conforto': 'home_comfort',
    'audio': 'audio',
    'alimentos_bebidas': 'food_drinks',
    'musica': 'music',
    'alimentos': 'food',
    'tablets_impressao_imagem': 'tablets_printing_imaging',
    'livros_importados': 'imported_books',
    'portateis_casa_forno_e_cafe': 'portable_home_oven_coffee',
    'fashion_esporte': 'fashion_sports',
    'artigos_de_natal': 'christmas_supplies',
    'fashion_roupa_infanto_juvenil': 'fashion_kids_teen',
    'dvds_blu_ray': 'dvds_blu_ray',
    'artes_e_artesanato': 'arts_and_crafts',
    'pc_gamer': 'gaming_pc',
    'moveis_quarto': 'bedroom_furniture',
    'cine_foto': 'cinema_photo',
    'fraldas_higiene': 'diapers_hygiene',
    'flores': 'flowers',
    'casa_conforto_2': 'home_comfort',
    'portateis_cozinha_e_preparadores_de_alimentos': 'portable_kitchen_appliances',
    'seguros_e_servicos': 'insurance_services',
    'moveis_colchao_e_estofado': 'mattress_upholstered_furniture',
    'cds_dvds_musicais': 'music_cds_dvds'
}

In [69]:
df2['product_category_en'] = df2['product_category_name'].replace(category_mapping)

In [70]:
df2

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_en
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,arts
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,babies
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,home_utilities
...,...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0,furniture_decor
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0,construction_tools_lighting
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0,bed_bath_table
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0,computer_accessories
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0,bed_bath_table

In [71]:
df2.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
product_category_en             0
dtype: int64

In [72]:
df2.duplicated().sum()

np.int64(0)

In [73]:
df2.shape

(32951, 10)

In [74]:
(df2['product_photos_qty']<0).sum()

np.int64(0)

In [75]:
(df2['product_weight_g']<0).sum()

np.int64(0)

In [76]:
(df2['product_length_cm']<0).sum()

np.int64(0)

In [77]:
(df2['product_height_cm']<0).sum()

np.int64(0)

In [81]:
(df2['product_width_cm']<0).sum()

np.int64(0)

In [82]:
df2.to_csv(r"C:\Users\gadis\Downloads\olist\Clean Datasets\products.csv",index=False, lineterminator="\n")

In [83]:
df3 = pd.read_csv(r"C:\Users\gadis\Downloads\olist\olist_order_reviews_dataset.csv")

In [84]:
df3.shape

(99224, 7)

In [85]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [86]:
df3.describe()

       review_score
count  99224.000000
mean       4.086421
std        1.347579
min        1.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000

In [87]:
df3.columns

Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='object')

In [88]:
df3.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [89]:
df3.duplicated().sum()

np.int64(0)

In [90]:
(df3['review_score']<0).sum()

np.int64(0)

In [91]:
df3['review_creation_date'] = pd.to_datetime(df3['review_creation_date'])

In [92]:
df3['review_creation_date'].head(20)

0    2018-01-18
1    2018-03-10
2    2018-02-17
3    2017-04-21
4    2018-03-01
5    2018-04-13
6    2017-07-16
7    2018-08-14
8    2017-05-17
9    2018-05-22
10   2017-12-23
11   2017-12-19
12   2018-02-16
13   2018-03-28
14   2017-04-30
15   2018-05-23
16   2018-01-18
17   2018-03-24
18   2017-09-29
19   2018-08-15
Name: review_creation_date, dtype: datetime64[ns]

In [93]:
df3['review_answer_timestamp']= pd.to_datetime(df3['review_answer_timestamp'])

In [94]:
df3

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01,2018-03-02 10:26:53
...,...,...,...,...,...,...,...
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN,2018-07-07,2018-07-14 17:18:30
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN,2017-12-09,2017-12-11 20:06:42
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22,2018-03-23 09:10:43
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN,2018-07-01,2018-07-02 12:59:13
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03,2017-07-03 21:01:49

In [95]:
df3.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [96]:
df3 = df3.drop('review_comment_title', axis=1)

In [97]:
df3

,review_id,order_id,review_score,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,2018-01-18,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,2018-03-10,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,2018-02-17,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,Recebi bem antes do prazo estipulado.,2017-04-21,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,Parabéns lojas lannister adorei comprar pela I...,2018-03-01,2018-03-02 10:26:53
...,...,...,...,...,...,...
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,2018-07-07,2018-07-14 17:18:30
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,2017-12-09,2017-12-11 20:06:42
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,"Excelente mochila, entrega super rápida. Super...",2018-03-22,2018-03-23 09:10:43
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,2018-07-01,2018-07-02 12:59:13
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,"meu produto chegou e ja tenho que devolver, po...",2017-07-03,2017-07-03 21:01:49

In [98]:
df3=df3.drop('review_comment_message',axis=1)

In [99]:
df3

,review_id,order_id,review_score,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,2018-01-18,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,2018-03-10,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,2018-02-17,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,2017-04-21,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,2018-03-01,2018-03-02 10:26:53
...,...,...,...,...,...
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,2018-07-07,2018-07-14 17:18:30
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,2017-12-09,2017-12-11 20:06:42
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,2018-03-22,2018-03-23 09:10:43
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,2018-07-01,2018-07-02 12:59:13
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,2017-07-03,2017-07-03 21:01:49

In [100]:
df3.to_csv(r"C:\Users\gadis\Downloads\olist\Clean Datasets\reviews.csv",index=False, lineterminator="\n")

In [101]:
df4 = pd.read_csv(r"C:\Users\gadis\Downloads\olist\olist_orders_dataset.csv")

In [102]:
df4.head(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [103]:
df4.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [104]:
df4.shape

(99441, 8)

In [105]:
df4['order_status'].unique()

array(['delivered', 'invoiced', 'shipped', 'processing', 'unavailable',
       'canceled', 'created', 'approved'], dtype=object)

In [106]:
df4.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [107]:
# List or tuple of column names
date_cols = ['order_purchase_timestamp', 'order_approved_at',
             'order_delivered_carrier_date', 'order_delivered_customer_date',
             'order_estimated_delivery_date']

# Convert each column to datetime
for col in date_cols:
    if col in df4.columns:  # make sure column exists
        df4[col] = pd.to_datetime(df4[col].astype(str), errors='coerce')

In [108]:
df4

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03

In [109]:
df4.to_csv(r"C:\Users\gadis\Downloads\olist\Clean Datasets\orders.csv",index=False, lineterminator="\n")

In [110]:
df5 = pd.read_csv(r"C:\Users\gadis\Downloads\olist\olist_order_payments_dataset.csv")

In [111]:
df5.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [112]:
df5.duplicated().sum()

np.int64(0)

In [113]:
df5.shape

(103886, 5)

In [114]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [115]:
df5['payment_type'].unique()

array(['credit_card', 'boleto', 'voucher', 'debit_card', 'not_defined'],
      dtype=object)

In [116]:
df5['payment_installments'].unique()

array([ 8,  1,  2,  3,  6,  5,  4, 10,  7, 12,  9, 13, 15, 24, 11, 18, 14,
       20, 21, 17, 22,  0, 16, 23])

In [117]:
df5['payment_value'].min()

0.0

In [118]:
df5['payment_value'].max()

13664.08

In [119]:
df5

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45
...,...,...,...,...,...
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

In [120]:
df5.to_csv(r"C:\Users\gadis\Downloads\olist\Clean Datasets\order_payment.csv",index=False, lineterminator="\n")

In [122]:
df6 = pd.read_csv(r"C:\Users\gadis\Downloads\olist\olist_order_items_dataset.csv")

In [123]:
df6.shape

(112650, 7)

In [124]:
df6.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [125]:
df6.duplicated().sum()

np.int64(0)

In [126]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [127]:
df6['shipping_limit_date']=pd.to_datetime(df6['shipping_limit_date'])

In [128]:
df6

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [129]:
df6['price'].min()

0.85

In [130]:
df6['freight_value'].min()

0.0

In [2]:
df6.to_csv(r"C:\Users\gadis\Downloads\olist\Clean Datasets\order_items.csv",index=False, lineterminator="\n")

NameError: name 'df6' is not defined

In [14]:
df7 = pd.read_csv(r"C:\Users\gadis\Downloads\olist\olist_geolocation_dataset.csv")

In [16]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [17]:
df7

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP
...,...,...,...,...,...
1000158,99950,-28.068639,-52.010705,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000161,99980,-28.388932,-51.846871,david canabarro,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [18]:
df7.shape

(1000163, 5)

In [19]:
df7.describe()

       geolocation_zip_code_prefix  geolocation_lat  geolocation_lng
count                 1.000163e+06     1.000163e+06     1.000163e+06
mean                  3.657417e+04    -2.117615e+01    -4.639054e+01
std                   3.054934e+04     5.715866e+00     4.269748e+00
min                   1.001000e+03    -3.660537e+01    -1.014668e+02
25%                   1.107500e+04    -2.360355e+01    -4.857317e+01
50%                   2.653000e+04    -2.291938e+01    -4.663788e+01
75%                   6.350400e+04    -1.997962e+01    -4.376771e+01
max                   9.999000e+04     4.506593e+01     1.211054e+02

In [20]:
df7.duplicated().sum()

np.int64(261831)

In [21]:
df7 = df7.drop_duplicates()

In [22]:
df7.duplicated().sum()

np.int64(0)

In [23]:
df7.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [24]:
df7['geolocation_city'].unique()

array(['sao paulo', 'são paulo', 'sao bernardo do campo', ..., 'ciríaco',
       'estação', 'vila lângaro'], shape=(8011,), dtype=object)

In [25]:
df7

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP
...,...,...,...,...,...
1000155,99965,-28.180655,-52.034367,agua santa,RS
1000156,99950,-28.072188,-52.011272,tapejara,RS
1000157,99950,-28.068864,-52.012964,tapejara,RS
1000158,99950,-28.068639,-52.010705,tapejara,RS
1000161,99980,-28.388932,-51.846871,david canabarro,RS

In [26]:
df7.to_csv(r"C:\Users\gadis\Downloads\olist\Clean Datasets\geolocation.csv",index=False, lineterminator="\n")

In [145]:
df8= pd.read_csv(r"C:\Users\gadis\Downloads\olist\olist_customers_dataset.csv")

In [147]:
df8.shape

(99441, 5)

In [148]:
df8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [149]:
df8.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [150]:
df8.duplicated().sum()

np.int64(0)

In [152]:
df8.to_csv(r"C:\Users\gadis\Downloads\olist\Clean Datasets\customers.csv",index=False, lineterminator="\n")

In [154]:
df8.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')